version: '2.0'

services:
  etherchain-light:
    build: ./explorer
    #restart: always
    ports:
      - 3000:3000
    links:
      - provider
    depends_on:
      - provider
    command: ["npm", "start"]
  provider:
    image: ethresearch/pyethapp-research
    volumes:
      - ./provider/default_data/config:/root/.config/pyethapp
      - ./provider/default_data/log:/root/log
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
    command: ["pyethapp", "run"]
